server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9093,kafka-3:9094

    producer:
      properties:
        spring.json.add.type.headers: false
        
  topic:
    name: alertas_infantiles

    
  datasource:
    url: jdbc:oracle:thin:@backduoccloud_high?TNS_ADMIN=/app/wallet
    username: ADMIN
    password: Secure1Password2Example
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true