server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9093,kafka-3:9094

    producer:
      properties:
        spring.json.add.type.headers: false
        
  topic:
    name: alertas_infantiles